import type { NextPage } from 'next'
import { useEffect, useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import md5 from 'md5'

const Page: NextPage = () => {

  const [inputString, setInputString] = useState("")

  function validateFormWithJS() {
    alert("form validating...")
  }

  function calculateMd5() {
    const output = document.getElementById("output")

    if (inputString === "") {
      output!.innerText = "Enter a valid string"
    } else {
      const newHash = md5(inputString)
      output!.innerText = newHash
    }
  }

  useEffect(() => {
    calculateMd5()
  }, [inputString])

  return (
    <div className="">
      <Head>
        <title>md5 Hash Generator - cheeky.tools</title>
        <meta name="description" content="This MD5 hash generator is a hashing tool for encoding strings, personal data and other information into databases and storage." />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <h1 className="text-center text-5xl font-bold underline">md5 Hash Generator</h1>
        <p className='mt-5'>Quickly compute the MD5 hash of any string. Other hashing tools can be found here.</p>
      </div>
      <div className="my-3">  
        <label htmlFor="message" className="block text-sm font-medium text-gray-900 dark:text-gray-400">Input String</label>
        <textarea id="message" value={inputString} onChange={(e) => setInputString(e.target.value)} rows={4} className="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" ></textarea>
        {/* <div onClick={calculateMd5} className="mt-3 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Compute md5</div> */}
      </div>

      <div className="mb-5 mt-8">
        <label htmlFor="output" className="block text-sm font-medium text-gray-900 dark:text-gray-300">Your md5 Hash</label>
        <div id="output" className="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 dark:shadow-sm-light" />
      </div>

      <p className="text-sm"><span className="font-bold underline uppercase">Note:</span> All content generated by this tool is done client-side (on your local computer) using JavaScript. None of your data is recorded or stored by us at all. Please view our <span className="text-blue-500">Privacy Policy</span> for more information.</p>
    </div>
  )
}

export default Page