import Link from "next/link"

export default function ToolDisclaimer() {
    return <>
    <p className="text-sm">
        <span className="font-bold underline uppercase">Note:</span>&nbsp;
        All content generated by this tool is done client-side (on your local computer) using JavaScript. None of your data is recorded or stored by us at all. 
        Please view our <span className="text-blue-500"><Link href="/privacy">Privacy Policy</Link></span> for more information.</p>
    </>
  }