import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mt-5">
        <h1 className="text-center text-2xl text-blue-500">cheeky.tools</h1>
      </main>

      <footer className="text-center text-xl mt-5">
          Powered by{' '}
          <a href="https://github.com/cheekyprorgammer" target="_blank" rel="noopener noreferrer">
            cheekyprogrammer
          </a>
      </footer>
    </div>
  )
}

export default Home
